version: '2'
services:
  app:
    image: jekyll/jekyll
    container_name: wakatakeru-blog
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: 'jekyll serve -s /usr/src/app --watch'
    ports:
      - "4000:4000"
